[package]
name = "ooze"
version = "0.2.0"
authors = ["zbidwell <ZBidwell@pacificinsight.com>"]
edition = "2018"

[dependencies]
glium = "*"
# rand = "*"
image = "*"
# glob = "*"
# toml = "*"
rusttype = "*"